#!/bin/bash

result=$(timeout 0.1s sway-audio-idle-inhibit --dry-print-both --ignore-app wayvibes)

if [ "$result" = "RUNNING" ]; then
    echo "{\"alt\":\"active\"}"
else
   echo "{\"alt\":\"not_active\"}"
fi
